### ISSUE TITLE
javascript大小写特性trick

### ISSUE THREAD

**Issue by pench3r** [w181496/Web-CTF-Cheatsheet#2]
"ı".toUpperCase() == 'I'，"ſ".toUpperCase() == 'S'
"K".toLowerCase() == 'k'

通过这个小特性可以绕过一些限制。

参考文章：https://www.leavesongs.com/HTML/javascript-up-low-ercase-tip.html

**Comment by w181496** [comment]
Thanks, 已更新該trick
